### ISSUE TITLE
geardatagrid will not connect to dashboard module (test file)

### ISSUE THREAD

**Issue by wrjac** [russell190/backpacker#17]
Not sure if I'm referencing the JSON output correctly or not. See bootgrid documentation for details

**Comment by jpuck** [comment]
From the looks of it, you are missing the JavaScript to actually initialize the object. At a minimum, I would expect to see something like:

```html
<script>
$("#gear").bootgrid();
</script>
```

**Comment by jpuck** [comment]
This should be fixed in #19
